### ISSUE TITLE
Should all packages mentioned in wiki be installed on CentOS?

### ISSUE THREAD

**Issue by alikhajeh1** [pyguy/ansible-hpe-software#4]
https://github.com/pyguy/ansible-hpe-software/wiki has a list of packages (such as `hp-ams` and `hp-health`) that don't seem to be installed on CentOS, should they be?

**Comment by pyguy** [comment]
for centos `hpe_project_ver` has the value of `current` which hp-ams and hp-health packages are deprecated on.
